disabled_rules:
  - trailing_comma

opt_in_rules:
  - empty_count
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - sorted_imports

excluded:
  - .build
  - Packages/*/.build
  - DerivedData
  - Sentinel.xcodeproj

line_length:
  warning: 120
  error: 140

type_body_length:
  warning: 300
  error: 450

file_length:
  warning: 500
  error: 700
